### ISSUE TITLE
Requerimientos 1. parte

### ISSUE THREAD

**Issue by AndresMorenoR** [ISWPOLI/Blockchain#24]
Documentación - Requerimientos - 1. parte.
**Tareas.**
- [x] Introducción.
- [x] Objetivos SMART.
- [x] Marco teórico.
- [x] Modelado de negocio (Canvas).
- [x] Problema de investigación.
- [x] Justificación.

**Comment by japrietoPoli** [comment]
Se subió la primera parte de la entrega 1
